### ISSUE TITLE
archive after 2020-06-10

### ISSUE THREAD

**Issue by Xuanlin309** [kenyoneda/mta-gtfs-rt-archive#1]
Hello, thank you so much for archiving gtfs-rt data. this is very helpful!!

It seems like archived file after 2020-06-10 can't be downloaded and suggesting "internal server error".

**Comment by kenyoneda** [comment]
@Xuanlin309 Sorry about that - I have not been maintaining this archive recently. The server I was running it on crashed without me knowing so there is no data from 2020-06-10 onward.

I have started it up again though!
